     
@base = https://localhost:7175

@productId = 2779ee47-10b0-4bd7-8342-404006aa1392

### options Request 

OPTIONS  {{base}}/api/products

### HEAD Request (Check for resources Existents)

HEAD   {{base}}/api/products/{{productId}}


###GEt Request (get product by id)

GET   {{base}}/api/products/{{productId}}?includeReview=true
###
GET   {{base}}/api/products/{{productId}}

### GET page for pagination 

GET   {{base}}/api/products?page=1&PageSize=4

###Create product
post  {{base}}/api/products
Content-Type: application/json

{
    "name" : "ldddove",
    "price" : 124
}